# Generated by Django 3.1 on 2020-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='document1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='information',
            name='document2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='information',
            name='document3',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='information',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
